### PR TITLE
Added  ability to set theme based on user data

### PR DESCRIPTION
**Pull request by anirudh411**
## Description
 - Added theming support based on theme object that will come at the time of login .
- Changed some default import of routes to lazy imports.

### Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by anirudh411** [comment]
### Custom theme Example
image

**Review by ShadabFaiz — COMMENTED** [review]
Which part of UI is themable and which are not? Is this information available anywhere?

**Comment by anirudh411** [comment]
> Which part of UI is themable and which are not? Is this information available anywhere? 

Every part or UI is theme based  . 
If you look at `uiContext.tsx` ,you will see that  if userData is present it will user's theme otherwise it will fallback to the default one.

**Comment by ShadabFaiz** [comment]
Are these UI as per expectation or something is missed in themeing functionality?
1.
FI 2-Theme
User cannot see datas of even rows.

2.
Projects
This is the iew of  Porject => Impact => Nested table

3.
Grant Period
Project => Grant Period.

4.
Create Project
Project Creation.

5.
Organisation Dashboard
Look at the currenct active project. Its all white. (Forget about the card size. That will be fixed by @realgcoding l)

**Comment by anirudh411** [comment]
@ShadabFaiz I am aware of these issues. This is happening  because of the incorrect usage of theme variables across the project.  I think the authors of these files would would be able to fix them easily.

**Review by ShadabFaiz — APPROVED** [review]

**Pull request merged**
